<?php
/**
 * sync-session.php
 *
 * Syncs the Laravel API login result into a PHP session.
 *
 * Security: requires a one-time `_sync_token` that was generated by the
 * Laravel login endpoint and stored in the PHP session at login time.
 * Without a valid token, no session data is written (prevents auth bypass).
 */
session_start();

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed.']);
    exit;
}

$input = json_decode(file_get_contents('php://input'), true);

// ── Session flag clear operations (safe — no user data written) ────────────
if (isset($input['clear_just_logged_in'])) {
    unset($_SESSION['just_logged_in']);
    echo json_encode(['success' => true]);
    exit;
}
if (isset($input['clear_must_change_password'])) {
    unset($_SESSION['must_change_password']);
    unset($_SESSION['just_logged_in']);
    echo json_encode(['success' => true]);
    exit;
}

// ── Session sync: requires a valid one-time sync token ────────────────────
if (isset($input['user'])) {
    $providedToken = $input['_sync_token'] ?? '';
    $storedToken   = $_SESSION['_pending_sync_token'] ?? '';

    // Validate: token must be non-empty, match, and not yet consumed
    if (
        empty($providedToken) ||
        empty($storedToken) ||
        !hash_equals($storedToken, $providedToken)
    ) {
        http_response_code(403);
        echo json_encode(['success' => false, 'error' => 'Invalid or missing sync token.']);
        exit;
    }

    // Consume the token immediately (one-time use)
    unset($_SESSION['_pending_sync_token']);

    // Write session data
    $_SESSION['user_id']               = $input['user']['id'];
    $_SESSION['user_name']             = $input['user']['name'];
    $_SESSION['user_email']            = $input['user']['email'];
    $_SESSION['user_role']             = $input['user']['role'];
    $_SESSION['user_municipality_id']  = $input['user']['municipality_id'] ?? null;
    $_SESSION['user_municipality_name']= $input['user']['municipality_name'] ?? null;
    $_SESSION['must_change_password']  = $input['user']['must_change_password'] ?? false;

    if ($_SESSION['must_change_password']) {
        $_SESSION['just_logged_in'] = true;
    }

    echo json_encode(['success' => true]);
    exit;
}

echo json_encode(['success' => false, 'error' => 'No action specified.']);
